### ISSUE TITLE
Cookie Expiration

### ISSUE THREAD

**Issue by Fenn3c401** [enzon19/reversetv#1]
Hi,
I've been using ReverseTV for a little while now (it's a lovely idea), the only problem being that I have to manually re-auth quite frequently.. There are two things I noticed about the the cookies for the Trakt API OAuth tokens in regards to that:
1. `refresh_token` is set as a session cookie, so it can't be used to fetch a new `access_token` in the next browser session. Any particular reason for this that I'm missing?
2. `access_token` is set to expire after 24 hours, they upped the valid-for period to [7 days](https://trakt.docs.apiary.io/reference/authentication-oauth) some time ago.

Oh, and beyond that I've got another two feature suggestions, which might be nice to have:
1. Have the title posters in the results be clickable and link to the respective Trakt.tv summary page.
2. Have the "Last Watched" section of the homepage also include movies.

But that's more of a side note, the need for manual re-authing is mostly annoying because it breaks the direct ReverseTV links I add to title summary pages on Trakt.tv through a userscript of mine.

**Comment by Fenn3c401** [comment]
> Hi! Thanks for your issue! I thought the repo was public 😂 I've made it public: https://github.com/enzon19/reversetv/issues If you don't mind reposting this there
> 
> But, yes... This is something that also bothers me.
> 
> About your suggestions:
> 
> 1. I don't think I understood correctly...
> 2. Strange. The movies appears for me.
> 
> I'll close here, if you don't mind.

Thanks for the quick reply, I was wondering why you hadn't open-sourced this one lol. Feel free to delete the old issue.
About:
1. When I go to e.g. https://reversetv.enzon19.com/movies/the-shawshank-redemption-1994 I can see that "Clancy Brown" also starred in "Lost" and "The Punisher", but to get to the corresponding Trakt.tv summary page https://trakt.tv/shows/marvel-s-the-punisher I have to manually search for the title on Trakt, which is a bit of a nuisance.
2. For me it exclusively lists tv shows, both in the "Last Watched" and "Random Items Watched" sections on https://reversetv.enzon19.com

**Comment by enzon19** [comment]
Ok, I think I fixed the problem with the expiration, I set the wrong `maxAge` for the cookie.

About your suggestions:
1. Do you mean something like this? A button to open the item in Trakt? The poster also should be clickable (it is not) <img width="301" height="399" alt="Image" src="https://github.com/user-attachments/assets/fc78bcb3-8b00-4095-bd91-685fbd3cc0de" />

2. I still don't know what is happening. Is your profile public in Trakt? Can you please share it? I'm not able to reproduce this. <img width="1300" height="748" alt="Image" src="https://github.com/user-attachments/assets/7c4983b9-39e4-40df-9978-34ce60e32f73" />

**Comment by Fenn3c401** [comment]
Alright, so the cookie expiration dates are looking good, that should be fixed, much appreciated!
About:
1. Something like that, right now on the homepage in the "Random Items" and "Last Watched" sections the posters are already clickable and link to the respective ReverseTV page, so I suppose if you wanted to keep that consistent you'd have to have the posters of the results link to the title's ReverseTV page as well. And then an "Open in Trakt" button per poster, maybe only visible on hover and styled similar to the red "Open in Trakt" button up top (on the results pages). I suppose you could make the posters of the actors clickable as well, have them link to the respective Trakt, TMDB or Wikipedia page.
2. Yeah, so after I read your reply I tried it again and suddenly it was working just fine.. So I investigated, I'm still not quite sure about the exact workings, but I think it happened in part because Trakt sets  
`https://api.trakt.tv/users/<username>/watched/movies => cache-control: public, max-age=16070400, s-maxage=3600`  
`https://api.trakt.tv/users/<username>/watched/shows => cache-control: max-age=0, private, must-revalidate`  
No idea why, but they have separate caching directives for the watched shows and movies endpoints, for shows because of max-age=0 it always re-validates, and for movies it just pulls from the disk cache.. which in my case was a response with an empty array for watched movies. But even if I bypass both the local and cloudflare's cache (and I just tried it with two different Trakt accounts) I can still more or less reliably reproduce getting the correct watched data for shows, but only an empty array for movies, which is only supposed to happen if the request is not authed correctly for a private account, except it is.. It seems like once an unauthed request for the watched movies of a private account is made, the empty response gets cached "somewhere" and is then used for subsequent authed requests.. That's my best guess anyway. Bottom line being: Whatever was/is going on is probably unrelated to ReverseTV, sorry for making you look for any bugs there.

**Comment by enzon19** [comment]
Thanks for all the help and suggestions! 

I'm not that satisfied with the website's current design and I'll probably do something about it next year. During that process, I'll work on that suggestion #1. And really thank you for investigating that #2, that's a very strange behavior from Trakt, but ok. 

I'll close this issue and open a new one for suggestion #1. Thanks!

**Comment by Fenn3c401** [comment]
Hi, sorry to bother you again, I was hoping the issue with the missing movies would go away by itself, as I wrote last time for a moment this was working fine again, but unfortunately things are still the same.. It's not just the two homepage sections but movies in general, including the results. Doesn't matter which browser, device and even with an alt Trakt account. However I noticed that you query the Trakt api using the username (can be uppercase), not the userslug (simplified lowercase version of username). That's supposed to work all the same, but it doesn't from my testing. Cause the one thing that fixes this for me is if I change my PascalCase username like `MyUserName` to `myusername`, then things start working again. I looked for you on Trakt where you use the same `enzon19` username, which happens to already be in all lowercase and is therefore identical to your userslug. It would be interesting to see if movies disappear on your end as well if you temporarily change your Trakt username to an uppercase version. Long story short, the watched movies endpoint is bugged and can misbehave when using the username instead of the userslug. Alternatively you can always just use `me` instead, works all the same.
